export const productActions = {
  DELETE_PRODUCT: "DELETE_PRODUCT",
  SAVE_PRODUCT_DETAILS: "SAVE_PRODUCT_DETAILS",
};

export const productDetailsActions = {
  DISPLAY_PRODUCT_DETAILS: "DISPLAY_PRODUCT_DETAILS",
  CHECK_PRODUCT_EXIST: "CHECK_PRODUCT_EXIST",
};
