export const productActions = {
  DELETE_PRODUCT: "DELETE_PRODUCT",
  SAVE_PRODUCT_DETAILS: "SAVE_PRODUCT_DETAILS",
  SORT_LIST_BY_NAME: "SORT_LIST_BY_NAME",
  SORT_LIST_BY_DATE: "SORT_LIST_BY_DATE",
};

export const productDetailsActions = {
  DISPLAY_PRODUCT_DETAILS: "DISPLAY_PRODUCT_DETAILS",
  CHECK_PRODUCT_EXIST: "CHECK_PRODUCT_EXIST",
  ADD_NEW_PRODUCT: "ADD_NEW_PRODUCT",
};
